SELECT EXTRACT(YEAR FROM eq.fecha_inventario) AS ANIO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 01 THEN 1 ELSE 0 END) AS ENERO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 02 THEN 1 ELSE 0 END) AS FEBRERO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 03 THEN 1 ELSE 0 END) AS MARZO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 04 THEN 1 ELSE 0 END) AS ABRIL,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 05 THEN 1 ELSE 0 END) AS MAYO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 06 THEN 1 ELSE 0 END) AS JUNIO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 07 THEN 1 ELSE 0 END) AS JULIO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 08 THEN 1 ELSE 0 END) AS AGOSTO,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 09 THEN 1 ELSE 0 END) AS SEPTIEMPRE,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 10 THEN 1 ELSE 0 END) AS OCTUBRE,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 11 THEN 1 ELSE 0 END) AS NOVIEMBRE,
SUM(CASE WHEN EXTRACT(MONTH FROM eq.fecha_inventario) = 12 THEN 1 ELSE 0 END) AS DICIEMBRE,
COUNT(eq.fecha) AS TOTAL
FROM equipos eq
GROUP BY EXTRACT(YEAR FROM eq.fecha_inventario);