SELECT 
TO_CHAR(A1.ANIO),
A1.PARTICION_1 AS PARTICION_1,
A1.PARTICION_2 AS PARTICION_2,
A1.PARTICION_3 AS PARTICION_3,
A1.PARTICION_4 AS PARTICION_4,
A1.PARTICION_MAS AS PARTICION_MAS,
A1.PARTICION_1 + A1.PARTICION_2 + A1.PARTICION_3 + A1.PARTICION_4 + A1.PARTICION_MAS AS TOTAL 
FROM
	(SELECT * FROM (SELECT EXTRACT(YEAR FROM fecha_inventario) AS ANIO, particiones AS particiones FROM asignaciones_equipos_discos)
	PIVOT
	(
	COUNT(1)
	FOR particiones
	IN (1 AS PARTICION_1,2 AS PARTICION_2,3 AS PARTICION_3,4 AS PARTICION_4,5 AS PARTICION_MAS)
	)) A1
UNION ALL

SELECT 'TOTAL', SUM(A1.PARTICION_1),SUM(A1.PARTICION_2),SUM(A1.PARTICION_3),SUM(A1.PARTICION_4),SUM(A1.PARTICION_MAS),SUM(A1.TOTAL) 
FROM
(
SELECT A1.ANIO,A1.PARTICION_1 AS PARTICION_1,A1.PARTICION_2 AS PARTICION_2,A1.PARTICION_3 AS PARTICION_3,A1.PARTICION_4 AS PARTICION_4,A1.PARTICION_MAS AS PARTICION_MAS,A1.PARTICION_1 + A1.PARTICION_2 + A1.PARTICION_3 + A1.PARTICION_4 + A1.PARTICION_MAS AS TOTAL FROM
(SELECT * FROM (SELECT EXTRACT(YEAR FROM FECHA_INVENTARIO) AS ANIO, particiones AS particiones FROM asignaciones_equipos_discos)
PIVOT
(
COUNT(1)
FOR particiones
IN (1 AS PARTICION_1,2 AS PARTICION_2,3 AS PARTICION_3,4 AS PARTICION_4,5 AS PARTICION_MAS)
)) A1
) A1
