CREATE OR REPLACE FUNCTION FUNC1 (CAP IN NUMERIC)
RETURN VARCHAR2
IS
CAPA NUMERIC := CAP;
CONT NUMERIC ;
MENSAJE VARCHAR2(300);
CURSOR SPACE_CURSOR IS SELECT AD.NOMBRE,AD.APELLIDOS,ASD.IDADMINISTRADOR,ES.idespacio,ES.DESCRIPCION,ES.CAPACIDAD,ES.RANGO FROM asignaciones_administradores ASD JOIN espacios ES ON ASD.IDespacio = ES.idespacio JOIN administradores AD ON ASD.IDADMINISTRADOR = AD.IDADMINISTRADOR WHERE ES.CAPACIDAD >= CAPA;
SPACE_VALUE SPACE_CURSOR%ROWTYPE;
BEGIN
	SELECT T1.TOTAL INTO CONT FROM (SELECT COUNT(*) AS TOTAL FROM
	(SELECT AD.NOMBRE,AD.APELLIDOS,ASD.IDADMINISTRADOR,ASD.idespacio,ES.DESCRIPCION,ES.CAPACIDAD,ES.RANGO FROM asignaciones_administradores ASD
		INNER JOIN
		espacios ES
		ON ASD.IDespacio = ES.idespacio
		INNER JOIN
		administradores AD
		ON ASD.IDADMINISTRADOR = AD.IDADMINISTRADOR
		WHERE ES.CAPACIDAD >= CAPA)T)T1;		
		IF CONT > 0 THEN	
		OPEN SPACE_CURSOR;
		LOOP
			FETCH SPACE_CURSOR INTO SPACE_VALUE;
			EXIT WHEN SPACE_CURSOR%NOTFOUND;
			MENSAJE := MENSAJE || '--';
			MENSAJE := MENSAJE || SPACE_VALUE.NOMBRE;
			MENSAJE := MENSAJE || '--';
			MENSAJE := MENSAJE || SPACE_VALUE.APELLIDOS;
			MENSAJE := MENSAJE || '--';
			MENSAJE := MENSAJE || SPACE_VALUE.DESCRIPCION;
			MENSAJE := MENSAJE || '--';
			MENSAJE := MENSAJE || SPACE_VALUE.RANGO;
		END LOOP;
		CLOSE SPACE_CURSOR;
		
		ELSE 
			MENSAJE := 'No hay registros';
		END IF;
	RETURN(MENSAJE);
END FUNC1;
BEGIN
 DBMS_OUTPUT.PUT_LINE(FUNC1(40));
END;