CREATE OR REPLACE PROCEDURE PROC1 
(MACI IN VARCHAR2, IP_EQ OUT VARCHAR2,PLACA OUT VARCHAR2,PROVEEDOR OUT VARCHAR2,
PROCESADOR OUT VARCHAR2,VERSION OUT VARCHAR2,VIDEO OUT VARCHAR2, NOMBRE_Q OUT VARCHAR2) IS
TMP_IDESPACIO NUMERIC;
TMP_CODIGO NUMERIC;
TMP_IDPROVE NUMERIC;
TMP_IDVIDEO NUMERIC;
TMP_IDPLACA NUMERIC;
TMP_MAC VARCHAR(50) :=MACI;
BEGIN
SELECT IDESPACIO,CODIGO,IP INTO TMP_IDESPACIO,TMP_CODIGO,IP_EQ FROM asignaciones_equipos_tarjetas WHERE MAC = TMP_MAC;
SELECT NOMBRE INTO PROVEEDOR FROM PROVEEDORES WHERE IDPROVEEDOR = (SELECT IDPROVEEDOR FROM equipos WHERE IDESPACIO = TMP_IDESPACIO AND CODIGO = TMP_CODIGO);
SELECT MODELO INTO VIDEO FROM tarjetas_video WHERE IDTARJETA = (SELECT IDTARJETA_VIDEO FROM equipos WHERE IDESPACIO = TMP_IDESPACIO AND CODIGO = TMP_CODIGO);
SELECT NOMBRE INTO NOMBRE_Q FROM equipos WHERE IDESPACIO = TMP_IDESPACIO AND CODIGO = TMP_CODIGO;
SELECT FABRICANTE INTO PLACA FROM modelos_placa WHERE IDPLACA = (SELECT IDPLACA FROM equipos WHERE IDESPACIO = TMP_IDESPACIO AND CODIGO = TMP_CODIGO);
SELECT NOMBRE,VERSION INTO PROCESADOR,VERSION FROM procesadores WHERE IDPROCESADOR = (SELECT PROCESADOR FROM equipos WHERE IDESPACIO = TMP_IDESPACIO AND CODIGO = TMP_CODIGO);
END PROC1;
DECLARE
IP_EQ VARCHAR2(100);
PLACA VARCHAR2(100);
PROVEEDOR VARCHAR2(100);
PROCESADOR VARCHAR2(100);
VIDEO VARCHAR2(100);
NOMBRE VARCHAR2(100);
VERSION VARCHAR2(100);
BEGIN
 PROC1('00:0b:6a:7d:b2:44',IP_EQ,PLACA,PROVEEDOR,PROCESADOR,VERSION,VIDEO,NOMBRE);
 DBMS_OUTPUT.PUT_LINE(TO_CHAR(NOMBRE) || '--' || TO_CHAR(PROVEEDOR) || '--' || TO_CHAR(PROCESADOR) || '--' || TO_CHAR(VERSION) || '--' || TO_CHAR(PLACA) || '--'  || TO_CHAR(VIDEO) || '--' || TO_CHAR(IP_EQ));
END;